In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.linear_model import LinearRegression

In [3]:
Data=pd.read_csv("Dataframe.csv")

In [13]:
Data.drop(Data.loc[1,:])

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
2,2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,5,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [20]:
y=np.array(Data.price).reshape(-1,1)

In [21]:
x=np.array(Data.drop('price',axis=1))

In [22]:
x.shape,y.shape

((21613, 19), (21613, 1))

In [23]:
kf=KFold(n_splits=3)

In [29]:
indices=list(kf.split(x))

In [31]:
indices[2]

(array([    0,     1,     2, ..., 14406, 14407, 14408]),
 array([14409, 14410, 14411, ..., 21610, 21611, 21612]))

In [27]:
i=1

for train,test in kf.split(x):
    print("\nTrain"+str(i),train)
    print("\nTest",test)
    i+=1

Train1 [ 7205  7206  7207 ... 21610 21611 21612]

Test [   0    1    2 ... 7202 7203 7204]

Train2 [    0     1     2 ... 21610 21611 21612]

Test [ 7205  7206  7207 ... 14406 14407 14408]

Train3 [    0     1     2 ... 14406 14407 14408]

Test [14409 14410 14411 ... 21610 21611 21612]

In [28]:
len(x),len(train),len(test)

(21613, 14409, 7204)

In [33]:
x_train1,y_train1=x[indices[0][0]],y[indices[0][0]]
x_train2,y_train2=x[indices[1][0]],y[indices[1][0]]

x_test1,y_test1=x[indices[0][1]],y[indices[0][1]]
x_test2,y_test2=x[indices[1][1]],y[indices[1][1]]

In [34]:
x_train1.shape

(14408, 19)

In [35]:
x_test1.shape

(7205, 19)

In [36]:
y_train1.shape

(14408, 1)

In [37]:
regressor=LinearRegression()
regressor.fit(x_train1,y_train1)
regressor.score(x_test1,y_test1)

0.7223994834143604

In [38]:
regressor.fit(x_train2,y_train2)
regressor.score(x_test2,y_test2)

0.7193375283268654

In [41]:
cross_val_score(regressor,x,y,cv=3)

array([0.72239948, 0.71933753, 0.72291521])

In [42]:
from sklearn.model_selection  import RepeatedKFold

In [47]:
rep_kf=RepeatedKFold(n_splits=2,n_repeats=2,random_state=40)

In [48]:
indices=list(rep_kf.split(x))
print(indices)

[(array([    0,     4,     7, ..., 21603, 21606, 21608]), array([    1,     2,     3, ..., 21610, 21611, 21612])), (array([    1,     2,     3, ..., 21610, 21611, 21612]), array([    0,     4,     7, ..., 21603, 21606, 21608])), (array([    0,     1,     9, ..., 21604, 21608, 21611]), array([    2,     3,     4, ..., 21609, 21610, 21612])), (array([    2,     3,     4, ..., 21609, 21610, 21612]), array([    0,     1,     9, ..., 21604, 21608, 21611]))]

In [49]:
i=1

for train,test in rep_kf.split(x):
    print("\nTrain"+str(i),train)
    print("\nTest",test)
    i+=1

Train1 [    0     4     7 ... 21603 21606 21608]

Test [    1     2     3 ... 21610 21611 21612]

Train2 [    1     2     3 ... 21610 21611 21612]

Test [    0     4     7 ... 21603 21606 21608]

Train3 [    0     1     9 ... 21604 21608 21611]

Test [    2     3     4 ... 21609 21610 21612]

Train4 [    2     3     4 ... 21609 21610 21612]

Test [    0     1     9 ... 21604 21608 21611]

In [50]:
regressor.fit(x_train1,y_train1)
regressor.score(x_test1,y_test1)

0.7223994834143604

In [51]:
regressor.fit(x_train2,y_train2)
regressor.score(x_test2,y_test2)

0.7193375283268654

In [52]:
cross_val_score(regressor,x,y,cv=rep_kf)

array([0.7291084 , 0.72141872, 0.73004319, 0.71750949])

In [53]:
from sklearn.linear_model import LogisticRegression

In [70]:
logistic=LogisticRegression(solver='liblinear')

TypeError: __init__() got an unexpected keyword argument 'c'

In [55]:
from sklearn.model_selection import StratifiedKFold

In [72]:
cancer_data=pd.read_csv('cancer_data.csv')

In [84]:
cancer_data=cancer_data.drop(['Unnamed: 0','Diagnosis'],axis=1)

In [85]:
x=cancer_data.drop('Outcome',axis=1)

In [86]:
y=cancer_data['Outcome']

In [87]:
skf=StratifiedKFold(n_splits=5,shuffle=True)

In [88]:
indices=list(skf.split(x,y))

In [89]:
indices

[(array([  0,   2,   3,   4,   5,   6,   9,  10,  11,  12,  13,  14,  15,
          16,  17,  18,  19,  20,  23,  24,  25,  26,  27,  28,  29,  30,
          33,  34,  35,  36,  38,  39,  41,  42,  43,  44,  45,  47,  48,
          51,  52,  53,  55,  56,  57,  59,  60,  62,  63,  64,  65,  67,
          68,  69,  71,  72,  73,  74,  75,  77,  78,  79,  80,  81,  82,
          83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  95,  96,  97,
          98, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
         113, 114, 115, 116, 117, 118, 119, 121, 122, 124, 125, 126, 127,
         129, 131, 132, 133, 134, 135, 137, 138, 139, 141, 142, 143, 144,
         146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 159,
         160, 161, 162, 163, 164, 167, 169, 170, 171, 173, 174, 175, 176,
         178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 192,
         193, 195, 196, 198, 200, 201, 202, 203, 205, 206, 207, 208, 209,
         211, 212, 213, 215, 216, 219, 220, 222, 224, 225, 227, 229, 230,
         232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
         245, 246, 247, 248, 249, 250, 252, 253, 255, 257, 258, 261, 262,
         263, 264, 268, 269, 272, 273, 274, 275, 277, 278, 279, 280, 281,
         282, 283, 285, 286, 287, 288, 289, 290, 291, 293, 294, 296, 297,
         298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310,
         312, 313, 314, 315, 316, 317, 318, 319, 320, 322, 323, 324, 325,
         326, 327, 328, 329, 330, 331, 333, 334, 335, 336, 337, 338, 340,
         341, 342, 343, 344, 345, 346, 348, 349, 350, 351, 352, 353, 354,
         355, 356, 357, 358, 359, 361, 363, 364, 365, 367, 368, 369, 370,
         371, 373, 376, 377, 378, 381, 382, 383, 384, 385, 386, 387, 388,
         389, 390, 391, 394, 395, 397, 398, 399, 400, 401, 402, 403, 404,
         406, 407, 408, 409, 410, 411, 412, 414, 415, 416, 417, 420, 421,
         422, 423, 424, 426, 427, 429, 430, 431, 432, 434, 435, 436, 437,
         438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 451,
         452, 454, 455, 456, 457, 458, 461, 462, 463, 467, 468, 469, 470,
         471, 472, 474, 476, 477, 478, 479, 481, 482, 483, 484, 485, 486,
         487, 488, 490, 492, 493, 494, 495, 497, 499, 500, 502, 503, 506,
         507, 508, 509, 510, 511, 512, 513, 514, 516, 517, 518, 519, 524,
         525, 526, 527, 528, 529, 531, 532, 534, 535, 536, 539, 542, 543,
         544, 545, 546, 547, 549, 550, 551, 552, 553, 556, 560, 561, 562,
         564, 565, 566, 567, 570, 571, 572, 573, 574, 575, 576, 577, 578,
         580, 581, 582, 583, 584, 585, 586, 587, 589, 590, 591, 592, 594,
         595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 607, 608,
         609, 610, 611, 612, 613, 615, 617, 619, 620, 621, 624, 625, 626,
         628, 629, 630, 632, 633, 634, 635, 636, 637, 638, 640, 641, 642,
         643, 645, 646, 647, 649, 650, 651, 652, 654, 655, 656, 657, 658,
         659, 661, 663, 664, 666, 667, 668, 669, 670, 671, 672, 673, 675,
         676, 677, 678, 679, 680, 681, 682, 683, 685, 686, 687, 688, 689,
         692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704,
         705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717,
         718, 720, 721, 722, 723, 724, 725, 726, 727, 728, 730, 731, 732,
         734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 747,
         749, 750, 751, 752, 753, 754, 755, 757, 758, 759, 761, 762, 763,
         765, 766, 767]),
  array([  1,   7,   8,  21,  22,  31,  32,  37,  40,  46,  49,  50,  54,
          58,  61,  66,  70,  76,  93,  94,  99, 100, 120, 123, 128, 130,
         136, 140, 145, 158, 165, 166, 168, 172, 177, 183, 191, 194, 197,
         199, 204, 210, 214, 217, 218, 221, 223, 226, 228, 231, 251, 254,
         256, 259, 260, 265, 266, 267, 270, 271, 276, 284, 292, 295, 311,
         321, 332, 339, 347, 360, 362, 366, 372, 374, 375, 379, 380, 392,
         393, 396, 405, 413, 418, 419, 425, 428, 433, 450, 453, 459, 460,
         464, 465, 466, 473, 475, 480, 489, 491, 496, 498, 501, 504, 505,
         515, 520, 521, 522, 523, 530, 533, 537, 538, 540, 541, 548, 554,
         555, 557, 558, 559, 563, 568, 569, 579, 588, 593, 606, 614, 616,
         618, 622, 623, 627, 631, 639, 644, 648, 653, 660, 662, 665, 674,
         684, 690, 691, 719, 729, 733, 746, 748, 756, 760, 764])),
 (array([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,  11,  14,  16,
          18,  19,  20,  21,  22,  23,  25,  26,  27,  28,  29,  30,  31,
          32,  33,  34,  35,  36,  37,  39,  40,  41,  42,  43,  44,  45,
          46,  47,  48,  49,  50,  51,  53,  54,  56,  58,  59,  60,  61,
          62,  64,  65,  66,  67,  68,  70,  71,  73,  76,  77,  78,  79,
          80,  81,  82,  83,  84,  85,  86,  87,  88,  91,  93,  94,  95,
          98,  99, 100, 102, 103, 104, 105, 106, 107, 108, 109, 111, 113,
         115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
         128, 130, 131, 132, 133, 135, 136, 137, 138, 139, 140, 141, 142,
         143, 144, 145, 147, 148, 149, 150, 151, 154, 155, 156, 158, 160,
         162, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
         177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
         191, 192, 193, 194, 195, 196, 197, 199, 200, 201, 203, 204, 205,
         206, 210, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222,
         223, 225, 226, 227, 228, 229, 230, 231, 233, 234, 235, 236, 238,
         239, 240, 241, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
         253, 254, 256, 259, 260, 261, 263, 264, 265, 266, 267, 270, 271,
         272, 273, 274, 275, 276, 277, 278, 279, 281, 282, 283, 284, 285,
         286, 287, 288, 289, 291, 292, 293, 294, 295, 297, 298, 300, 301,
         302, 303, 304, 307, 308, 309, 310, 311, 312, 314, 316, 317, 319,
         320, 321, 322, 323, 324, 325, 327, 328, 330, 331, 332, 334, 337,
         339, 340, 342, 344, 345, 346, 347, 350, 351, 354, 356, 357, 358,
         359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 372,
         374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386,
         391, 392, 393, 395, 396, 398, 399, 400, 401, 402, 403, 405, 406,
         408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420,
         421, 423, 425, 426, 427, 428, 429, 432, 433, 434, 435, 436, 438,
         439, 440, 441, 442, 444, 445, 446, 447, 448, 449, 450, 451, 452,
         453, 454, 455, 456, 457, 459, 460, 461, 463, 464, 465, 466, 467,
         469, 470, 471, 472, 473, 474, 475, 476, 478, 480, 481, 483, 484,
         485, 488, 489, 490, 491, 492, 493, 494, 495, 496, 498, 499, 500,
         501, 502, 503, 504, 505, 506, 508, 509, 510, 513, 514, 515, 517,
         520, 521, 522, 523, 525, 526, 527, 529, 530, 531, 532, 533, 534,
         536, 537, 538, 539, 540, 541, 542, 543, 545, 546, 547, 548, 549,
         551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563,
         564, 567, 568, 569, 570, 571, 572, 573, 575, 576, 577, 578, 579,
         580, 581, 582, 583, 585, 586, 588, 589, 590, 592, 593, 594, 596,
         597, 598, 599, 600, 601, 603, 604, 605, 606, 607, 608, 610, 613,
         614, 615, 616, 617, 618, 619, 621, 622, 623, 625, 627, 628, 629,
         631, 632, 633, 634, 635, 637, 638, 639, 641, 642, 643, 644, 645,
         646, 647, 648, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659,
         660, 662, 663, 665, 666, 667, 668, 669, 670, 672, 674, 675, 676,
         677, 678, 679, 680, 681, 683, 684, 686, 687, 688, 689, 690, 691,
         694, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708,
         709, 710, 711, 712, 713, 715, 716, 717, 719, 721, 724, 725, 726,
         727, 729, 730, 732, 733, 734, 735, 736, 737, 738, 739, 743, 744,
         745, 746, 748, 751, 752, 754, 756, 757, 758, 759, 760, 761, 762,
         763, 764, 766]),
  array([  4,  12,  13,  15,  17,  24,  38,  52,  55,  57,  63,  69,  72,
          74,  75,  89,  90,  92,  96,  97, 101, 110, 112, 114, 129, 134,
         146, 152, 153, 157, 159, 161, 163, 176, 190, 198, 202, 207, 208,
         209, 211, 224, 232, 237, 242, 255, 257, 258, 262, 268, 269, 280,
         290, 296, 299, 305, 306, 313, 315, 318, 326, 329, 333, 335, 336,
         338, 341, 343, 348, 349, 352, 353, 355, 371, 373, 387, 388, 389,
         390, 394, 397, 404, 407, 422, 424, 430, 431, 437, 443, 458, 462,
         468, 477, 479, 482, 486, 487, 497, 507, 511, 512, 516, 518, 519,
         524, 528, 535, 544, 550, 565, 566, 574, 584, 587, 591, 595, 602,
         609, 611, 612, 620, 624, 626, 630, 636, 640, 649, 661, 664, 671,
         673, 682, 685, 692, 693, 695, 696, 714, 718, 720, 722, 723, 728,
         731, 740, 741, 742, 747, 749, 750, 753, 755, 765, 767])),
 (array([  0,   1,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  17,  18,  20,  21,  22,  24,  25,  26,  27,  28,  30,
          31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  42,  43,  44,
          46,  47,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
          60,  61,  62,  63,  64,  66,  67,  68,  69,  70,  72,  73,  74,
          75,  76,  77,  78,  80,  81,  82,  83,  84,  86,  87,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         105, 106, 107, 109, 110, 112, 114, 116, 117, 118, 120, 121, 122,
         123, 124, 127, 128, 129, 130, 131, 133, 134, 136, 139, 140, 143,
         144, 145, 146, 147, 148, 150, 152, 153, 154, 155, 157, 158, 159,
         160, 161, 162, 163, 164, 165, 166, 168, 169, 170, 171, 172, 174,
         176, 177, 180, 181, 182, 183, 187, 188, 189, 190, 191, 192, 194,
         195, 197, 198, 199, 202, 203, 204, 205, 206, 207, 208, 209, 210,
         211, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
         225, 226, 228, 229, 230, 231, 232, 235, 237, 238, 240, 241, 242,
         251, 254, 255, 256, 257, 258, 259, 260, 261, 262, 265, 266, 267,
         268, 269, 270, 271, 272, 273, 274, 276, 278, 279, 280, 281, 282,
         283, 284, 285, 287, 288, 289, 290, 292, 293, 295, 296, 299, 302,
         303, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
         317, 318, 319, 321, 322, 324, 325, 326, 327, 329, 332, 333, 334,
         335, 336, 338, 339, 340, 341, 342, 343, 345, 346, 347, 348, 349,
         350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362,
         363, 366, 367, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380,
         381, 382, 383, 384, 386, 387, 388, 389, 390, 391, 392, 393, 394,
         395, 396, 397, 398, 400, 403, 404, 405, 406, 407, 409, 410, 413,
         416, 417, 418, 419, 421, 422, 423, 424, 425, 427, 428, 429, 430,
         431, 433, 435, 436, 437, 438, 439, 442, 443, 444, 445, 446, 447,
         448, 449, 450, 451, 453, 454, 457, 458, 459, 460, 461, 462, 463,
         464, 465, 466, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
         478, 479, 480, 481, 482, 484, 485, 486, 487, 488, 489, 491, 492,
         493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505,
         507, 508, 509, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520,
         521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 533, 535, 537,
         538, 539, 540, 541, 544, 545, 546, 547, 548, 549, 550, 552, 553,
         554, 555, 557, 558, 559, 560, 562, 563, 564, 565, 566, 567, 568,
         569, 570, 571, 572, 573, 574, 575, 578, 579, 583, 584, 585, 586,
         587, 588, 591, 593, 595, 596, 597, 598, 599, 600, 601, 602, 603,
         604, 605, 606, 609, 610, 611, 612, 614, 616, 617, 618, 619, 620,
         621, 622, 623, 624, 625, 626, 627, 628, 630, 631, 633, 634, 635,
         636, 637, 639, 640, 642, 644, 645, 647, 648, 649, 651, 652, 653,
         654, 655, 656, 657, 660, 661, 662, 663, 664, 665, 667, 668, 669,
         671, 672, 673, 674, 675, 676, 677, 678, 681, 682, 683, 684, 685,
         686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698,
         699, 701, 705, 706, 708, 711, 712, 713, 714, 715, 717, 718, 719,
         720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732,
         733, 735, 736, 737, 738, 740, 741, 742, 743, 745, 746, 747, 748,
         749, 750, 751, 752, 753, 754, 755, 756, 757, 759, 760, 761, 762,
         764, 765, 767]),
  array([  2,  16,  19,  23,  29,  41,  45,  48,  65,  71,  79,  85,  88,
         104, 108, 111, 113, 115, 119, 125, 126, 132, 135, 137, 138, 141,
         142, 149, 151, 156, 167, 173, 175, 178, 179, 184, 185, 186, 193,
         196, 200, 201, 212, 227, 233, 234, 236, 239, 243, 244, 245, 246,
         247, 248, 249, 250, 252, 253, 263, 264, 275, 277, 286, 291, 294,
         297, 298, 300, 301, 304, 320, 323, 328, 330, 331, 337, 344, 364,
         365, 368, 369, 370, 385, 399, 401, 402, 408, 411, 412, 414, 415,
         420, 426, 432, 434, 440, 441, 452, 455, 456, 467, 483, 490, 506,
         510, 531, 532, 534, 536, 542, 543, 551, 556, 561, 576, 577, 580,
         581, 582, 589, 590, 592, 594, 607, 608, 613, 615, 629, 632, 638,
         641, 643, 646, 650, 658, 659, 666, 670, 679, 680, 700, 702, 703,
         704, 707, 709, 710, 716, 734, 739, 744, 758, 763, 766])),
 (array([  1,   2,   4,   5,   7,   8,   9,  10,  11,  12,  13,  15,  16,
          17,  19,  21,  22,  23,  24,  25,  27,  29,  31,  32,  33,  36,
          37,  38,  39,  40,  41,  43,  44,  45,  46,  47,  48,  49,  50,
          52,  54,  55,  56,  57,  58,  59,  61,  62,  63,  65,  66,  67,
          69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  82,
          85,  86,  87,  88,  89,  90,  92,  93,  94,  96,  97,  99, 100,
         101, 102, 104, 107, 108, 109, 110, 111, 112, 113, 114, 115, 117,
         119, 120, 123, 124, 125, 126, 128, 129, 130, 132, 134, 135, 136,
         137, 138, 139, 140, 141, 142, 145, 146, 148, 149, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 163, 165, 166, 167, 168,
         171, 172, 173, 174, 175, 176, 177, 178, 179, 182, 183, 184, 185,
         186, 188, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
         201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
         215, 217, 218, 221, 223, 224, 226, 227, 228, 229, 231, 232, 233,
         234, 235, 236, 237, 239, 240, 241, 242, 243, 244, 245, 246, 247,
         248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
         261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 273, 275,
         276, 277, 278, 279, 280, 284, 285, 286, 287, 289, 290, 291, 292,
         294, 295, 296, 297, 298, 299, 300, 301, 302, 304, 305, 306, 307,
         308, 309, 311, 312, 313, 315, 316, 318, 319, 320, 321, 322, 323,
         324, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
         338, 339, 340, 341, 342, 343, 344, 345, 347, 348, 349, 350, 352,
         353, 355, 356, 357, 358, 360, 362, 364, 365, 366, 368, 369, 370,
         371, 372, 373, 374, 375, 376, 378, 379, 380, 381, 382, 383, 385,
         386, 387, 388, 389, 390, 392, 393, 394, 396, 397, 398, 399, 401,
         402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414,
         415, 416, 418, 419, 420, 422, 424, 425, 426, 427, 428, 429, 430,
         431, 432, 433, 434, 435, 437, 438, 440, 441, 443, 444, 445, 446,
         449, 450, 451, 452, 453, 455, 456, 457, 458, 459, 460, 461, 462,
         463, 464, 465, 466, 467, 468, 469, 472, 473, 475, 476, 477, 479,
         480, 482, 483, 485, 486, 487, 489, 490, 491, 492, 493, 495, 496,
         497, 498, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511, 512,
         515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 526, 528, 529,
         530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542,
         543, 544, 547, 548, 550, 551, 552, 554, 555, 556, 557, 558, 559,
         561, 562, 563, 564, 565, 566, 568, 569, 571, 572, 573, 574, 576,
         577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589,
         590, 591, 592, 593, 594, 595, 597, 601, 602, 605, 606, 607, 608,
         609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 620, 622, 623,
         624, 626, 627, 628, 629, 630, 631, 632, 633, 634, 636, 637, 638,
         639, 640, 641, 642, 643, 644, 646, 647, 648, 649, 650, 651, 652,
         653, 654, 655, 656, 658, 659, 660, 661, 662, 663, 664, 665, 666,
         668, 670, 671, 673, 674, 679, 680, 681, 682, 684, 685, 687, 688,
         689, 690, 691, 692, 693, 695, 696, 697, 700, 702, 703, 704, 705,
         707, 709, 710, 711, 714, 716, 718, 719, 720, 722, 723, 725, 726,
         728, 729, 730, 731, 732, 733, 734, 739, 740, 741, 742, 744, 746,
         747, 748, 749, 750, 751, 753, 754, 755, 756, 758, 760, 762, 763,
         764, 765, 766, 767]),
  array([  0,   3,   6,  14,  18,  20,  26,  28,  30,  34,  35,  42,  51,
          53,  60,  64,  68,  81,  83,  84,  91,  95,  98, 103, 105, 106,
         116, 118, 121, 122, 127, 131, 133, 143, 144, 147, 150, 162, 164,
         169, 170, 180, 181, 187, 189, 203, 216, 219, 220, 222, 225, 230,
         238, 272, 274, 281, 282, 283, 288, 293, 303, 310, 314, 317, 325,
         346, 351, 354, 359, 361, 363, 367, 377, 384, 391, 395, 400, 417,
         421, 423, 436, 439, 442, 447, 448, 454, 470, 471, 474, 478, 481,
         484, 488, 494, 499, 500, 509, 513, 514, 525, 527, 545, 546, 549,
         553, 560, 567, 570, 575, 596, 598, 599, 600, 603, 604, 619, 621,
         625, 635, 645, 657, 667, 669, 672, 675, 676, 677, 678, 683, 686,
         694, 698, 699, 701, 706, 708, 712, 713, 715, 717, 721, 724, 727,
         735, 736, 737, 738, 743, 745, 752, 757, 759, 761])),
 (array([  0,   1,   2,   3,   4,   6,   7,   8,  12,  13,  14,  15,  16,
          17,  18,  19,  20,  21,  22,  23,  24,  26,  28,  29,  30,  31,
          32,  34,  35,  37,  38,  40,  41,  42,  45,  46,  48,  49,  50,
          51,  52,  53,  54,  55,  57,  58,  60,  61,  63,  64,  65,  66,
          68,  69,  70,  71,  72,  74,  75,  76,  79,  81,  83,  84,  85,
          88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
         101, 103, 104, 105, 106, 108, 110, 111, 112, 113, 114, 115, 116,
         118, 119, 120, 121, 122, 123, 125, 126, 127, 128, 129, 130, 131,
         132, 133, 134, 135, 136, 137, 138, 140, 141, 142, 143, 144, 145,
         146, 147, 149, 150, 151, 152, 153, 156, 157, 158, 159, 161, 162,
         163, 164, 165, 166, 167, 168, 169, 170, 172, 173, 175, 176, 177,
         178, 179, 180, 181, 183, 184, 185, 186, 187, 189, 190, 191, 193,
         194, 196, 197, 198, 199, 200, 201, 202, 203, 204, 207, 208, 209,
         210, 211, 212, 214, 216, 217, 218, 219, 220, 221, 222, 223, 224,
         225, 226, 227, 228, 230, 231, 232, 233, 234, 236, 237, 238, 239,
         242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
         255, 256, 257, 258, 259, 260, 262, 263, 264, 265, 266, 267, 268,
         269, 270, 271, 272, 274, 275, 276, 277, 280, 281, 282, 283, 284,
         286, 288, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300,
         301, 303, 304, 305, 306, 310, 311, 313, 314, 315, 317, 318, 320,
         321, 323, 325, 326, 328, 329, 330, 331, 332, 333, 335, 336, 337,
         338, 339, 341, 343, 344, 346, 347, 348, 349, 351, 352, 353, 354,
         355, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370,
         371, 372, 373, 374, 375, 377, 379, 380, 384, 385, 387, 388, 389,
         390, 391, 392, 393, 394, 395, 396, 397, 399, 400, 401, 402, 404,
         405, 407, 408, 411, 412, 413, 414, 415, 417, 418, 419, 420, 421,
         422, 423, 424, 425, 426, 428, 430, 431, 432, 433, 434, 436, 437,
         439, 440, 441, 442, 443, 447, 448, 450, 452, 453, 454, 455, 456,
         458, 459, 460, 462, 464, 465, 466, 467, 468, 470, 471, 473, 474,
         475, 477, 478, 479, 480, 481, 482, 483, 484, 486, 487, 488, 489,
         490, 491, 494, 496, 497, 498, 499, 500, 501, 504, 505, 506, 507,
         509, 510, 511, 512, 513, 514, 515, 516, 518, 519, 520, 521, 522,
         523, 524, 525, 527, 528, 530, 531, 532, 533, 534, 535, 536, 537,

In [90]:
x_train1,y_train1=x.loc[indices[0][0]],y.loc[indices[0][0]]
x_train2,y_train2=x.loc[indices[1][0]],y.loc[indices[1][0]]

x_test1,y_test1=x.loc[indices[0][1]],y.loc[indices[0][1]]
x_test2,y_test2=x.loc[indices[1][1]],y.loc[indices[1][1]]

In [91]:
x_train1.shape

(614, 8)

In [92]:
logistic.fit(x_train1,y_train1)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [93]:
logistic.score(x_test1,y_test1)

0.7207792207792207

In [94]:
logistic.fit(x_train2,y_train2)
logistic.score(x_test2,y_test2)

0.8116883116883117